#!/usr/bin/env python3
#
# parsy documentation build configuration file, created by
# sphinx-quickstart on Mon Sep 25 22:24:17 2017.
#
# This file is execfile()d with the current directory set to its
# containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#


# sys.path.insert(0, os.path.abspath("../src"))


# -- General configuration ------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#
# needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = ["sphinx.ext.viewcode"]

# Add any paths that contain templates here, relative to this directory.
templates_path = ["_templates"]

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
#
# source_suffix = ['.rst', '.md']
source_suffix = ".rst"

# The master toctree document.
master_doc = "index"

# General information about the project.
project = "parsy"
copyright = "2017, Jeanine Adkisson, Luke Plant"
author = "Jeanine Adkisson"

# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.
#
# The short X.Y version.
version = "2.0"
# The full version, including alpha/beta/rc tags.
release = "2.0"

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = None

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This patterns also effect to html_static_path and html_extra_path
exclude_patterns = ["_build", "Thumbs.db", ".DS_Store"]

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = "sphinx"

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = False


# -- Options for HTML output ----------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = "furo"

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
#

# html_theme_options = {
#     "dark_css_variables": {
#         "color-problematic": "#ee5151",

#         # Base Colors
#         "color-foreground-primary": "#ffffffcc",  # for main text and headings
#         "color-foreground-secondary": "#9ca0a5",  # for secondary text
#         "color-foreground-muted": "#81868d",  # for muted text
#         "color-foreground-border": "#666666",  # for content borders

#         "color-background-primary": "#171a1c",  # for content
#         "color-background-secondary": "#23251f",  # for navigation + ToC
#         "color-background-hover": "#323B37ff",  # for navigation-item hover
#         "color-background-hover--transparent": "#323B3700",
#         "color-background-border": "#303335",  # for UI borders
#         "color-background-item": "#444",  # for "background" items (eg: copybutton)

#         # Announcements
#         "color-announcement-background": "#000000dd",
#         "color-announcement-text": "#eeebee",

#         # Brand colors
#         "color-brand-primary": "#2b8cee",
#         "color-brand-content": "#368ce2",

#         # Highlighted text (search)
#         "color-highlighted-background": "#083563",

#         # GUI Labels
#         "color-guilabel-background": "#08356380",
#         "color-guilabel-border": "#13395f80",

#         # API documentation
#         "color-highlight-on-target": "#333300",

#         # Admonitions
#         "color-admonition-background": "#18181a",
#     },
# }

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ["_static"]


# -- Options for HTMLHelp output ------------------------------------------

# Output file base name for HTML help builder.
htmlhelp_basename = "parsydoc"


# -- Options for LaTeX output ---------------------------------------------

latex_elements = {
    # The paper size ('letterpaper' or 'a4paper').
    #
    # 'papersize': 'letterpaper',
    # The font size ('10pt', '11pt' or '12pt').
    #
    # 'pointsize': '10pt',
    # Additional stuff for the LaTeX preamble.
    #
    # 'preamble': '',
    # Latex figure (float) alignment
    #
    # 'figure_align': 'htbp',
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [
    (master_doc, "parsy.tex", "parsy Documentation", "Jeanine Adkisson", "manual"),
]


# -- Options for manual page output ---------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [(master_doc, "parsy", "parsy Documentation", [author], 1)]


# -- Options for Texinfo output -------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    (master_doc, "parsy", "parsy Documentation", author, "parsy", "One line description of project.", "Miscellaneous"),
]
